version: '3'

services:
  faulty:
    image: fireharp/faulty:v0.1.1
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:3000 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
